### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by tocacyy** [MyCryptoCoins/TravelFlex#2]
In file included from main.h:11:0,
                 from checkpoints.cpp:10:
script.h:302:14: error: ‘CScript::CScript(int64_t)’ cannot be overloaded
     explicit CScript(int64_t b)          { operator<<(b); }
              ^
script.h:301:14: error: with ‘CScript::CScript(long int)’
     explicit CScript(long b)           { operator<<(b); }
              ^
script.h:307:14: error: ‘CScript::CScript(uint64_t)’ cannot be overloaded
     explicit CScript(uint64_t b)         { operator<<(b); }
              ^
script.h:306:14: error: with ‘CScript::CScript(long unsigned int)’
     explicit CScript(unsigned long b)  { operator<<(b); }
              ^
script.h:320:14: error: ‘CScript& CScript::operator<<(int64_t)’ cannot be overloaded
     CScript& operator<<(int64_t b)          { return push_int64(b); }
              ^
script.h:319:14: error: with ‘CScript& CScript::operator<<(long int)’
     CScript& operator<<(long b)           { return push_int64(b); }
              ^
script.h:325:14: error: ‘CScript& CScript::operator<<(uint64_t)’ cannot be overloaded
     CScript& operator<<(uint64_t b)         { return push_uint64(b); }
              ^
script.h:324:14: error: with ‘CScript& CScript::operator<<(long unsigned int)’
     CScript& operator<<(unsigned long b)  { return push_uint64(b); }
              ^
makefile.unix:186: recipe for target 'obj/checkpoints.o' failed
make: *** [obj/checkpoints.o] Error 1

**Comment by Beirdo** [comment]
This is in progress and is not intended to be used yet.
